// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB1gxCzsw52bMyZ_fZy9vJr2vnWVCb91k',
    appId: '1:553011840130:web:23715e3c0543365d4da09b',
    messagingSenderId: '553011840130',
    projectId: 'quizapp-2f066',
    authDomain: 'quizapp-2f066.firebaseapp.com',
    storageBucket: 'quizapp-2f066.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTeF08xzWIltI8TiCK6XNsNats4AKDedE',
    appId: '1:553011840130:android:afb35cec5f51975f4da09b',
    messagingSenderId: '553011840130',
    projectId: 'quizapp-2f066',
    storageBucket: 'quizapp-2f066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6seOJ36IlNubsqWGwnxenlWqU39Lu66E',
    appId: '1:553011840130:ios:ba0ab62e255d2b8a4da09b',
    messagingSenderId: '553011840130',
    projectId: 'quizapp-2f066',
    storageBucket: 'quizapp-2f066.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6seOJ36IlNubsqWGwnxenlWqU39Lu66E',
    appId: '1:553011840130:ios:ba0ab62e255d2b8a4da09b',
    messagingSenderId: '553011840130',
    projectId: 'quizapp-2f066',
    storageBucket: 'quizapp-2f066.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB1gxCzsw52bMyZ_fZy9vJr2vnWVCb91k',
    appId: '1:553011840130:web:16ec2010d01df7de4da09b',
    messagingSenderId: '553011840130',
    projectId: 'quizapp-2f066',
    authDomain: 'quizapp-2f066.firebaseapp.com',
    storageBucket: 'quizapp-2f066.appspot.com',
  );
}
